# secrets.IMAGE_NAME
#
# secrets.REGISTRY_URI
# secrets.REGISTRY_USER
# secrets.REGISTRY_PASS

name: Prod

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Extract Docker meta
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.REGISTRY_URI }}/${{ secrets.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},priority=900
            type=semver,pattern={{major}}.{{minor}},priority=900
            type=ref,event=branch,priority=600
            type=ref,event=pr,priority=600
            type=sha,format=long,prefix=,priority=100

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          push: true
